query GetMyProAnalytics {
  myProAnalytics {
    byClub {
      clubId
      clubName
      tournaments
      winningsCents
    }
    byBuyIn {
      buyInCents
      tournaments
      winningsCents
    }
  }
}
