query GetTournamentFieldNotes($tournamentId: ID!) {
  tournamentFieldNotes(tournamentId: $tournamentId) {
    clubPlayer {
      id
      displayName
    }
    note {
      id
      body
      style
      tags {
        id
        kind
        tag
      }
    }
  }
}
