query GetPlayerNote($subjectClubPlayerId: ID!) {
  playerNote(subjectClubPlayerId: $subjectClubPlayerId) {
    ...PlayerNoteFields
  }
}

query GetMyPlayerNotes {
  myPlayerNotes {
    ...PlayerNoteFields
  }
}

fragment PlayerNoteFields on PlayerNote {
  id
  subjectClubPlayerId
  body
  style
  createdAt
  updatedAt
  subject {
    id
    clubId
    displayName
  }
  tags {
    id
    kind
    tag
  }
  showdownObservations {
    id
    tournamentId
    description
    createdAt
  }
}
